### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by reneeb** [vti/mojolicious-plugin-tweet_button#2]
Hi,

can you release a new version of this module? The latest patch isn't on CPAN yet...

Kind regards,
Renée

**Comment by vti** [comment]
I am afraid I don't have time to adapt it to the new Mojolicious version :D

**Comment by reneeb** [comment]
Can you give mit CO-MAINT permissions on PAUSE?

**Comment by vti** [comment]
Done!
